name = "cf-ai-chat"
main = "src/index.ts"
compatibility_date = "2025-09-23"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

# ✅ Use SQLite-backed DO storage (required on Free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDO"]
